name: JadonSmithPhotography
favicon: null
layout_spectrum: 0.77001
typography_spectrum: 0.34303
title: Jadon Smith Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140f15'
    - '#e4dae5'
    - '#8883a7'
    - '#454157'
    - '#e9a071'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
