name: JadonSmithPhotography
favicon: null
layout_spectrum: 0.43648
typography_spectrum: 0.34303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffeff'
    - '#3867b7'
    - '#9fcdfe'
    - '#cfd500'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
